#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified by JOMBLOSSH                            #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Allah                                       #"
echo -e "# JSTFREENET                                         #"
echo -e "# My Family                                     #"
echo -e "# All Admin & All Member                                        #"
echo -e "# Horas Siregar                                 #"
echo -e "# Support Jomblossh                                 #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
